"""Added User model

Revision ID: 186be741cd49
Revises: 37b8d137fd24
Create Date: 2023-03-08 12:19:10.248405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186be741cd49'
down_revision = '37b8d137fd24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
