"""Added Location model

Revision ID: 831e38e1af21
Revises: 186be741cd49
Create Date: 2023-03-08 12:50:38.151774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831e38e1af21'
down_revision = '186be741cd49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    # ### end Alembic commands ###
