"""Fixing issues

Revision ID: f8fa67e14de4
Revises: 0e9a5690ec0a
Create Date: 2023-03-08 17:26:02.708397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8fa67e14de4'
down_revision = '0e9a5690ec0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('restaurant_locations', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('iftar_time', sa.Integer(), nullable=True))
    sa.ForeignKeyConstraint(['iftar_time'], ['id'])
    sa.ForeignKeyConstraint(['restaurant_locations'], ['id'])
    # op.create_foreign_key(None, 'locations', 'iftar_tables', ['iftar_time'], ['id'])
    # op.create_foreign_key(None, 'locations', 'restaurants', ['restaurant_locations'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'iftar_time')
    op.drop_column('locations', 'restaurant_locations')
    # ### end Alembic commands ###
